name: CI/CD Pipeline

on:
  #Manually trigger workflow runs
  workflow_dispatch:
  #Trigger workflow on push from master/main branch
  push:
    branches: [ master ]

jobs:
  # Unit Test job
  tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    #Steps:
    steps:
      #Check out
      - uses: actions/checkout@v3
      - name: Setup java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      #Run tests
      - name: Run Tests
        run: mvn -B test
  # Build job
  build:
    name: My First Pipeline
    # Run on Ubuntu latest
    runs-on: ubuntu-latest
    #Steps:
    steps:
      #Check out
      - uses: actions/checkout@v3