name: CI/CD Pipeline

on:
  #Manually trigger workflow runs
  workflow_dispatch:
  #Trigger workflow on push from master/main branch
  push:
    branches: [ master ]
env:
  REGISTRY: ghcr.io

jobs:
  # Unit Test job
  tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    #Steps:
    steps:
      #Check out
      - uses: actions/checkout@v3
      - name: Setup java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          # This is an alternative way to do what is done below
          #cache: 'maven'

      # Setup maven cache
      - name: Cache maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      #Run tests
      - name: Run Tests
        run: mvn -B test
  # Build job
  build:
    # Depends on tests
    needs: tests
    name: Build
    # Run on Ubuntu latest
    runs-on: ubuntu-latest
    #Steps:
    steps:
      #Check out
      - uses: actions/checkout@v3
      # Setup Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      # Build app using Maven
      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml
      - run: mkdir staging && cp target/*.jar staging

      # Upload JAR artifact
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v3
        with:
          # Set artifact name
          name: Runnablejar
          #From this path
          path: staging

  # Deploy to GHCR
  push-image-gchr:
    needs: build
    name: Deploy Images to GHCR
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
          # Remember to logout from Docker registry after completion
          logout: true

      - name: 'Build Docker image'
        run: |
          docker build . --tag ghcr.io/christianhougaardpedersen/devops-demo:latest
          docker push ghcr.io/christianhougaardpedersen/devops-demo:latest
